<?php
/**
 * @file
 * @todo add hash table cleaning
 */

/**
 * Implements hook_menu()
 */
function freelance_grabber_menu() {
  $items = array();

  $items['grabber/freelansimru'] = array(
    'title' => 'freelance grabber',
    'page callback' => 'freelance_grabber_freelansimru_grab',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['grabber'] = array(
    'title' => 'grabber',
    'page callback' => 'freelance_grabber_list_grabbers',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['grabber/clear-hashes'] = array(
    'title' => 'grabber',
    'page callback' => 'freelance_grabber_grabbers_clear_hashes',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Menu callback. Display list of avaliable grabbers.
 */
function freelance_grabber_list_grabbers() {
  $items = freelance_grabber_menu();
  unset($items['grabber']);
  $links = array();
  foreach ($items as $key => $item) {
    $links[] = array(
      'href' => $key,
      'title' => $item['title']
    );
  }
  return array(
    '#theme' => 'links',
    '#links' => $links
  );
}

/**
 * @todo make graber work in background
 */
function freelance_grabber_freelansimru_queue() {
  $url = 'http://freelansim.ru/tasks?page=' . $page_num . '&q=drupal';
  $url = 'http://freelansim.ru/tasks?page=' . $page_num . '&categories=web_all_inclusive,web_design,web_html,web_programming,web_prototyping,web_test,web_other';
  $site_url = 'http://freelansim.ru';
  $html = file_get_html($url);

  $pagination = $html->find('.pagination a');
  $count = count($pagination);
  $total_pages = &drupal_static(__FUNCTION__ . ':total_pages', (int) $pagination[$count-2]->plaintext);

//  $total_pages = (int) $pagination[$count-2]->plaintext;

//  if ($total_pages > 5) {
    print get_class($html); // simple_html_dom
    exit($pagination[$count-2]->plaintext);
    $queue = DrupalQueue::get('freelance_grabber_freelansimru', TRUE);
    $queue->createQueue();
    drupal_cron_run();
    for ($i = 1; $total_pages >= $i; $i++) {
      freelance_grabber_freelansimru_queue($i);
    }
    $queue->createItem(array('html' => $html));
//  }
}

/**
 * Main freelansim.ru grabber function
 * Get all items from specific reqest (e.g. q=drupal)
 */
function _freelance_grabber_freelansimru_grab($query, $path = 'http://freelansim.ru/tasks') {

  $url = url($path, array('query' => $query)) ;
  $site_url = 'http://freelansim.ru';
  $html = file_get_html($url);
  $body_array = &drupal_static(__FUNCTION__, array());
  $i = &drupal_static(__FUNCTION__ . ':iterator', 0);
  $elements = (array) $html->find("div#tasks_list div.tasks div.task");
  if (count($elements)) {
    foreach ($elements as $element) {
      $description = $element->find('div.description', 0)->plaintext;
      $link_url = $element->find('div.title a', 0)->href;
      $link_title = $element->find('div.title', 0)->title;
      if (!$link_title) {
        $link_title = $element->find('div.title a', 0)->plaintext;
      }
      $published = $element->find('div.published', 0)->plaintext;
      $link = l($link_title, $site_url . $link_url);
      $item = array();

      $item['link'] = $link;
      $item['teaser'] = $description;

      // Check if current item already has been processed.
      if (!freelance_grabber_freelansimru_grab_tiser_process($item)) {
        continue;
      }

      // published date can change, so include it later then pass data to
      // freelance_grabber_freelansimru_grab_tiser_process()
      $item['published'] = $published;
      $body_array[$i] = $item;
      $i++;
    }
    // Check other pages
    // restrict total checked pages to 15
    if ($query['page'] < 15) {
      $query['page']++;
      $body_array += _freelance_grabber_freelansimru_grab($query);
    }
  }
  return $body_array;
}

/**
 * Chech if teaser already has been processed.
 * If no,insert hash in to table hash
 * @param array $item
 * - $item['link']
 * - $item['teaser']
 * @return bool FALSE if teser already processed
 */
function freelance_grabber_freelansimru_grab_tiser_process($item) {
  $string = implode($item);
  $md5 = md5($string);
  $hash = db_select('freelance_grabber_hash', 'fgh')->fields('fgh', array('hash'))->condition('fgh.hash', $md5)->execute()->fetchField();
  if (!$hash) {
    $record = array(
      'created' => REQUEST_TIME,
      'hash' => $md5
    );
    drupal_write_record('freelance_grabber_hash', $record);
    return TRUE;
  }
  return FALSE;
}

/**
 * Run grabbing and send emails
 */
function freelance_grabber_freelansimru_grab($type) {
  global $language;
  @ignore_user_abort(TRUE);
  drupal_set_time_limit(360);
  // settings.
  $to = 'dimasikov@gmail.com';
  $queries = array(
    'drupal' => array(
      'page' => 1,
      'q' => 'drupal'
    ),
    'all_sites' => array(
      'page' => 1,
      'categories' => 'web_all_inclusive,web_design,web_html,web_programming,web_prototyping,web_test,web_other'
    )
  );
  // go!
  if (isset($queries[$type])) {
    $body_array = _freelance_grabber_freelansimru_grab($queries[$type]);
    if ($body_array) {
      $message = drupal_mail('freelance_grabber', 'freelansimru', $to, $language, array('body_array' => $body_array));
      // if messages hasn't been sended, provide an ability to resend them later.
      if (!$message['result']) {
        $md5_list = array();
        foreach ($body_array as $body_array_item) {
          unset($body_array_item['published']);
          $string = implode($body_array_item);
          $md5_list[] = md5($string);
        }
        $num = db_delete('freelance_grabber_hash')
            ->condition('hash', $md5_list)
            ->execute();
        print 'Enable to send messages';
//        return 'Enable to send messages';
        exit;
      }
      print 'success';
//      return 'success';
      exit;
    }
    print 'No new projects';
//    return 'No new projects';
    exit;
  }
  else {
    print 'Unknown type';
//    return 'Unknown type';
    exit;
  }
}

/**
 * Implements hook_mail()
 */
function freelance_grabber_mail($key, &$message, $params) {

  $headers = array(
    'X-Mailer' => variable_get('site_name', 'Drupal'),
    'Content-Type' => 'text/html; charset=UTF-8;'
  );

  switch ($key) {
    case 'freelansimru':
      $body_array = $params['body_array'];
      $message['subject'] = t('New projects on freelansim.ru, from !datetime', array(
        '!datetime' => format_date(REQUEST_TIME, 'custom', 'Y, F d H:i')
      ));
      $items = array();
      foreach ($body_array as $body_array_item) {
        $link = $body_array_item['link'];
        $teaser = $body_array_item['teaser'];
        $published = $body_array_item['published'];
        $body = implode("\n<br>", array($link, $published, $teaser));
        $items[] = nl2br($body . "\n\n");
      }
      $message['body'][] = theme('item_list', array('items' => $items, 'type' => 'ol'));
      $message['headers'] = array_merge($message['headers'], $headers);
      break;
  }
}

/**
 * Implements hook_cron().
 */
function freelance_grabber_cron() {
  // clean hash table
  $delete_from_timstamp = REQUEST_TIME - 60 * 60 * 24 * 14; // 14 days
  $num = db_delete('freelance_grabber_hash')->condition('freelance_grabber_hash.created', $delete_from_timstamp, '<')->execute();
  watchdog('freelance_grabber', '!num items was deleted from last cron runing', array('!num' => $num));
}

/**
 * Clear hash table
 */
function freelance_grabber_grabbers_clear_hashes() {
  $num = db_delete('freelance_grabber_hash')->execute();
  exit($num . ' was deleted.');
}